kind: pipeline
name: social-notify

steps:
- name: start notify slack 
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: cicd
    template: >
        Build {{build.number}} of {{build.branch}} started on {{repo.name}}. {{build.link}}

---
kind: pipeline
name: unit-test 

steps:
- name: node unit test
  image: node 
  commands:
    - npm install
    - npm test

---
kind: pipeline
type: ssh
name: default

server: 
    host: 165.22.104.56 
    user: root
    ssh_key: 
        from_secret: key002

steps: 
- name: clone and set up secrets
  commands:
    - cd /root/ 
    - sh cloneinit.sh 
    - sh setupsecrets.sh
- name: auth server
  commands:
    - gcloud config set project zoa001 
    - gcloud auth activate-service-account zoa-service-acct@zoa001.iam.gserviceaccount.com --key-file=/root/secrets/.creds.json
- name: cloudbuild microservice-fileupload-download 
  commands:
    - cd /root/zoa/microservice-fileupload-download 
    - gcloud builds submit
#- name: docker compose (deploy) 
#  commands:
#    - cd /root/zoa
#    - docker-compose up
depends_on:
- default
---
kind: pipeline
name: social-notify-status

steps:
- name: start notify slack 
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: cicd
    template: >
        Build {{build.number}} of {{build.branch}} started on {{repo.name}}. {{build.link}}
- name: end notify slack 
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: cicd
    template: >
      {{#success build.status}}
        Build {{build.number}} of {{build.branch}} on {{repo.name}} successful. {{build.link}}
      {{else}}
        Build {{build.number}} of {{build.branch}} on {{repo.name}} failed. Please fix!. {{build.link}}
      {{/success}}
depends_on:
- default
