steps: 
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "asia.gcr.io/$PROJECT_ID/fileserver:v1", "-t", "asia.gcr.io/$PROJECT_ID/fileserver:v10","."]
      env: 
        - 'PROJECT_ID=zoa001'
images: ["asia.gcr.io/$PROJECT_ID/fileserver:v1"]

